version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - fpm
    php-fpm:
        image: php:8-fpm
        volumes:
            - ./src:/var/www/html
        networks:
            - fpm
networks:
    fpm:
        driver: bridge